# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line  you're not using Docker
image: ubuntu:latest

before_script:
  - echo "Before script "
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - chmod 755 *.sh
    - ./build.sh

